### PR TITLE
Other network support

### PR DESCRIPTION
**Pull request by ianhe8x**
for #33

### CODE REVIEW

**Comment by ianhe8x** [comment]
will need tests to cover the new usage of cli.
and make README more clear for the new usage.

**Comment by ianhe8x** [comment]
@benxgao have a look if you have time.

**Comment by benxgao** [comment]
> @benxgao have a look if you have time.

I do not have enough context to take the review for now, if this is an urgent PR, just do whatever you think it should be. And I am not sure if it is our high priority work at this moment.

Later on, when we start with the Agile process, we could look into creating tickets, adding definition of done, etc. Or even we could think about task/ticket sizing, and PR code sizing, review practice, etc.

**Comment by ianhe8x** [comment]
> > @benxgao have a look if you have time.
> 
> I do not have enough context to take the review for now, if this is an urgent PR, just do whatever you think it should be. And I am not sure if it is our high priority work at this moment.
> 
> Later on, when we start with the Agile process, we could look into creating tickets, adding definition of done, etc. Or even we could think about task/ticket sizing, and PR code sizing, review practice, etc.

Not really asking you to do anything with this PR. only want to keep you in the loop. As for your opinions of processes, i appreciate them, but would rather use internal channels instead of discussing here.

**Comment by benxgao** [comment]
> > > @benxgao have a look if you have time.
> > 
> > 
> > I do not have enough context to take the review for now, if this is an urgent PR, just do whatever you think it should be. And I am not sure if it is our high priority work at this moment.
> > Later on, when we start with the Agile process, we could look into creating tickets, adding definition of done, etc. Or even we could think about task/ticket sizing, and PR code sizing, review practice, etc.
> 
> Not really asking you to do anything with this PR. only want to keep you in the loop. As for your opinions of processes, i appreciate them, but would rather use internal channels instead of discussing here.

Thanks for keeping me in the loop. Yeah, will discuss more in the channel next week. 

Now, enjoy your weekend! :))

**Pull request merged**
